code --install-extension aaron-bond.better-comments
code --install-extension alexisvt.flutter-snippets
code --install-extension BendixMa.dart-data-class-generator
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension golang.go
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension liviuschera.noctis
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension moyu.snapcode
code --install-extension ms-python.python
code --install-extension Nash.awesome-flutter-snippets
code --install-extension PKief.material-icon-theme
code --install-extension TakumiI.markdowntable
code --install-extension thenikso.github-plus-theme
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension yzhang.markdown-all-in-one